import type { Menu, Tenant } from "./types";

/**
 * Mock dataset standing in for the POS public API until the team leader ships it.
 * Shapes match `lib/api/types.ts` exactly, so swapping in the real API is a
 * one-file change in `client.ts`. Prices are KWD strings (3dp).
 */

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const MOCK_TENANT: Tenant = {
  slug: "noor",
  businessName: "Noor Kitchen",
  businessNameAr: "مطبخ نور",
  businessType: "RESTAURANT",
  tagline: "Levantine grill & mezze, made fresh in Salmiya",
  taglineAr: "مشاوي ومقبلات شامية تُحضّر طازجة في السالمية",
  logo: null,
  coverImage: img("1517248135467-4c7edcad34c4", 1600),
  currency: "KWD",
  rating: 4.8,
  ratingCount: 1243,
  priceLevel: 2,
  hours: "Daily · 12:00 PM – 1:00 AM",
  hoursAr: "يومياً · ١٢:٠٠ ظهراً – ١:٠٠ صباحاً",
  isOpenNow: true,
  orderTypes: ["TAKEAWAY", "DINE_IN", "DELIVERY"],
  offers: [
    {
      id: "of_grill",
      title: "Weekend Grill Feast",
      titleAr: "وليمة المشاوي في عطلة نهاية الأسبوع",
      subtitle: "Mixed grill platters for the whole family, all weekend long.",
      subtitleAr: "صحون مشاوي مشكّلة للعائلة طوال عطلة نهاية الأسبوع.",
      badge: "30% OFF",
      badgeAr: "خصم ٣٠٪",
      image: img("1555939594-58d7cb561ad1", 1400),
      href: "/s/noor/c/grill",
    },
    {
      id: "of_saj",
      title: "Fresh Saj, Rolled to Order",
      titleAr: "صاج طازج يُلفّ حسب الطلب",
      subtitle: "Try the chicken shawarma saj — hot off the griddle.",
      subtitleAr: "جرّب شاورما الدجاج بالصاج — ساخنة من الصاج.",
      badge: "NEW",
      badgeAr: "جديد",
      image: img("1561651823-34feb02250e4", 1400),
      href: "/s/noor/c/sandwiches",
    },
    {
      id: "of_delivery",
      title: "Free Delivery Over 5 KWD",
      titleAr: "توصيل مجاني فوق ٥ د.ك",
      subtitle: "On orders delivered to Salmiya & Hawally.",
      subtitleAr: "على الطلبات إلى السالمية وحولي.",
      badge: "FREE DELIVERY",
      badgeAr: "توصيل مجاني",
      image: img("1504674900247-0877df9cc836", 1400),
    },
  ],
  branches: [
    { id: "br_salmiya", name: "Salmiya", nameAr: "السالمية", area: "Salem Al Mubarak St", areaAr: "شارع سالم المبارك" },
    { id: "br_kuwaitcity", name: "Kuwait City", nameAr: "مدينة الكويت", area: "Al Soor St", areaAr: "شارع السور" },
    { id: "br_jabriya", name: "Jabriya", nameAr: "الجابرية", area: "Block 1B", areaAr: "قطعة ١ب" },
  ],
  // Brand colors — stands in for what the merchant picks in the POS dashboard.
  theme: { primary: "#3b5bdb", primaryDeep: "#2f49b0", accent: "#0ca678" },
  // Page-block order on the storefront home.
  sectionOrder: ["hero", "offers", "menu"],
};

export const MOCK_MENU: Menu = {
  categories: [
    { id: "cat_mezze", parentId: null, name: "Cold Mezze", nameAr: "مقبلات باردة", slug: "cold-mezze", sortOrder: 1 },
    { id: "cat_hot", parentId: null, name: "Hot Mezze", nameAr: "مقبلات ساخنة", slug: "hot-mezze", sortOrder: 2 },
    { id: "cat_grill", parentId: null, name: "From the Grill", nameAr: "من المشاوي", slug: "grill", sortOrder: 3 },
    { id: "cat_sandwich", parentId: null, name: "Saj & Sandwiches", nameAr: "صاج وسندويتشات", slug: "sandwiches", sortOrder: 4 },
    { id: "cat_drinks", parentId: null, name: "Drinks", nameAr: "مشروبات", slug: "drinks", sortOrder: 5 },
    // Sub-categories of Drinks (POS Category.parentId tree)
    { id: "cat_drinks_hot", parentId: "cat_drinks", name: "Hot Drinks", nameAr: "مشروبات ساخنة", slug: "hot-drinks", sortOrder: 1 },
    { id: "cat_drinks_cold", parentId: "cat_drinks", name: "Cold Drinks", nameAr: "مشروبات باردة", slug: "cold-drinks", sortOrder: 2 },
    { id: "cat_sweets", parentId: null, name: "Sweets", nameAr: "حلويات", slug: "sweets", sortOrder: 6 },
  ],
  products: [
    {
      id: "p_hummus",
      categoryId: "cat_mezze",
      name: "Hummus Beiruti",
      nameAr: "حمص بيروتي",
      description: "Stone-ground chickpeas, tahini, lemon, a pool of green olive oil.",
      descriptionAr: "حمص مطحون مع طحينة وليمون وزيت زيتون أخضر.",
      basePrice: "1.250",
      images: [{ url: img("1635887455483-3e2e8c8b0c0f"), isPrimary: true }],
      tags: ["mezze"],
      vegetarian: true,
      popular: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [
        {
          id: "mg_hummus_top",
          name: "Make it a meal",
          nameAr: "اجعلها وجبة",
          required: false,
          minSelect: 0,
          maxSelect: 3,
          modifiers: [
            { id: "m_pine", name: "Pine nuts", nameAr: "صنوبر", price: "0.500", isDefault: false },
            { id: "m_meat", name: "Spiced lamb", nameAr: "لحم متبّل", price: "1.000", isDefault: false },
            { id: "m_bread", name: "Extra saj bread", nameAr: "خبز صاج إضافي", price: "0.250", isDefault: false },
          ],
        },
      ],
    },
    {
      id: "p_mutabal",
      categoryId: "cat_mezze",
      name: "Mutabbal",
      nameAr: "متبل",
      description: "Smoked aubergine whipped with tahini and pomegranate.",
      descriptionAr: "باذنجان مدخّن مخفوق مع الطحينة والرمان.",
      basePrice: "1.350",
      images: [{ url: img("1576749872435-ff88a71c1ae2"), isPrimary: true }],
      tags: ["mezze"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_fattoush",
      categoryId: "cat_mezze",
      name: "Fattoush",
      nameAr: "فتوش",
      description: "Crisp greens, sumac, mint, toasted saj, pomegranate molasses.",
      descriptionAr: "خضار مقرمشة مع سماق ونعناع وخبز محمّص ودبس رمان.",
      basePrice: "1.500",
      images: [{ url: img("1512621776951-a57141f2eefd"), isPrimary: true }],
      tags: ["salad"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_kibbeh",
      categoryId: "cat_hot",
      name: "Kibbeh",
      nameAr: "كبة",
      description: "Crisp bulgur shells, spiced lamb and toasted pine nuts. Four pieces.",
      descriptionAr: "كبة مقرمشة محشوة باللحم والصنوبر. أربع قطع.",
      basePrice: "1.750",
      images: [{ url: img("1633945274405-b6c8069047b0"), isPrimary: true }],
      tags: ["hot"],
      popular: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_rakakat",
      categoryId: "cat_hot",
      name: "Cheese Rakakat",
      nameAr: "رقائق جبنة",
      description: "Golden pastry rolls of melting akkawi cheese. Five pieces.",
      descriptionAr: "رقائق ذهبية محشوة بجبنة عكاوي. خمس قطع.",
      basePrice: "1.500",
      images: [{ url: img("1565299624946-b28f40a0ae38"), isPrimary: true }],
      tags: ["hot"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_mixedgrill",
      categoryId: "cat_grill",
      name: "Mixed Grill Platter",
      nameAr: "مشاوي مشكّلة",
      description: "Shish taouk, lamb kebab, kofta and a lamb chop over saffron rice.",
      descriptionAr: "شيش طاووق وكباب لحم وكفتة وريش غنم على أرز بالزعفران.",
      basePrice: "4.750",
      images: [{ url: img("1555939594-58d7cb561ad1"), isPrimary: true }],
      tags: ["grill", "signature"],
      popular: true,
      spicy: false,
      hasVariants: true,
      variants: [
        { id: "v_grill_one", name: "For one", nameAr: "لشخص", price: "4.750", isDefault: true },
        { id: "v_grill_two", name: "For two", nameAr: "لشخصين", price: "8.500", isDefault: false },
        { id: "v_grill_family", name: "Family (4)", nameAr: "عائلي (٤)", price: "15.750", isDefault: false },
      ],
      modifierGroups: [
        {
          id: "mg_grill_side",
          name: "Choose a side",
          nameAr: "اختر طبقاً جانبياً",
          required: true,
          minSelect: 1,
          maxSelect: 1,
          modifiers: [
            { id: "m_rice", name: "Saffron rice", nameAr: "أرز بالزعفران", price: "0.000", isDefault: true },
            { id: "m_fries", name: "Fries", nameAr: "بطاطس", price: "0.000", isDefault: false },
            { id: "m_grilledveg", name: "Grilled vegetables", nameAr: "خضار مشوية", price: "0.250", isDefault: false },
          ],
        },
        {
          id: "mg_grill_sauce",
          name: "Sauces",
          nameAr: "صلصات",
          required: false,
          minSelect: 0,
          maxSelect: 4,
          modifiers: [
            { id: "m_garlic", name: "Garlic toum", nameAr: "ثومية", price: "0.150", isDefault: false },
            { id: "m_chili", name: "Chili", nameAr: "حار", price: "0.150", isDefault: false },
            { id: "m_tahini", name: "Tahini", nameAr: "طحينة", price: "0.150", isDefault: false },
          ],
        },
      ],
    },
    {
      id: "p_taouk",
      categoryId: "cat_grill",
      name: "Shish Taouk",
      nameAr: "شيش طاووق",
      description: "Charcoal-grilled marinated chicken skewers, garlic, pickles.",
      descriptionAr: "أسياخ دجاج متبّلة مشوية على الفحم مع الثوم والمخلل.",
      basePrice: "3.250",
      images: [{ url: img("1432139555190-58524dae6a55"), isPrimary: true }],
      tags: ["grill"],
      hasVariants: false,
      variants: [],
      modifierGroups: [
        {
          id: "mg_taouk_sauce",
          name: "Sauces",
          nameAr: "صلصات",
          required: false,
          minSelect: 0,
          maxSelect: 3,
          modifiers: [
            { id: "m_garlic2", name: "Garlic toum", nameAr: "ثومية", price: "0.150", isDefault: true },
            { id: "m_chili2", name: "Chili", nameAr: "حار", price: "0.150", isDefault: false },
          ],
        },
      ],
    },
    {
      id: "p_kofta",
      categoryId: "cat_grill",
      name: "Lamb Kofta",
      nameAr: "كفتة غنم",
      description: "Hand-minced lamb, parsley and onion, grilled over charcoal.",
      descriptionAr: "لحم غنم مفروم مع بقدونس وبصل، مشوي على الفحم.",
      basePrice: "3.500",
      images: [{ url: img("1529692236671-f1f6cf9683ba"), isPrimary: true }],
      tags: ["grill"],
      spicy: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_shawarma",
      categoryId: "cat_sandwich",
      name: "Chicken Shawarma Saj",
      nameAr: "شاورما دجاج صاج",
      description: "Shaved chicken, garlic, pickles and fries rolled in saj.",
      descriptionAr: "شاورما دجاج مع ثومية ومخلل وبطاطس ملفوفة بالصاج.",
      basePrice: "1.250",
      images: [{ url: img("1561651823-34feb02250e4"), isPrimary: true }],
      tags: ["sandwich"],
      popular: true,
      hasVariants: true,
      variants: [
        { id: "v_shaw_reg", name: "Regular", nameAr: "عادي", price: "1.250", isDefault: true },
        { id: "v_shaw_large", name: "Large", nameAr: "كبير", price: "1.750", isDefault: false },
      ],
      modifierGroups: [
        {
          id: "mg_shaw_extra",
          name: "Add extras",
          nameAr: "إضافات",
          required: false,
          minSelect: 0,
          maxSelect: 4,
          modifiers: [
            { id: "m_cheese", name: "Cheese", nameAr: "جبنة", price: "0.250", isDefault: false },
            { id: "m_extragarlic", name: "Extra garlic", nameAr: "ثوم إضافي", price: "0.100", isDefault: false },
            { id: "m_spicy", name: "Make it spicy", nameAr: "اجعلها حارة", price: "0.000", isDefault: false },
          ],
        },
      ],
    },
    {
      id: "p_falafel",
      categoryId: "cat_sandwich",
      name: "Falafel Wrap",
      nameAr: "ساندويتش فلافل",
      description: "Crisp falafel, tahini, tomato, pickles and mint in saj.",
      descriptionAr: "فلافل مقرمشة مع طحينة وطماطم ومخلل ونعناع في صاج.",
      basePrice: "1.000",
      images: [{ url: img("1547058671-d1e4b9e2dc26"), isPrimary: true }],
      tags: ["sandwich"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_mint_lemon",
      categoryId: "cat_drinks_cold",
      name: "Mint Lemonade",
      nameAr: "ليمون بالنعناع",
      description: "Fresh lemon blended with mint and a touch of orange blossom.",
      descriptionAr: "ليمون طازج مخفوق مع النعناع ولمسة من ماء الزهر.",
      basePrice: "0.950",
      images: [{ url: img("1556679343-c7306c1976bc"), isPrimary: true }],
      tags: ["drink"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_jellab",
      categoryId: "cat_drinks_cold",
      name: "Jallab",
      nameAr: "جلاب",
      description: "Date and grape molasses with rose water, pine nuts and crushed ice.",
      descriptionAr: "دبس التمر والعنب مع ماء الورد والصنوبر والثلج المجروش.",
      basePrice: "1.100",
      images: [{ url: img("1497534446932-c925b458314a"), isPrimary: true }],
      tags: ["drink"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_karak",
      categoryId: "cat_drinks_hot",
      name: "Karak Chai",
      nameAr: "شاي كرك",
      description: "Spiced milk tea simmered with cardamom and a touch of saffron.",
      descriptionAr: "شاي بالحليب يُغلى مع الهيل ولمسة من الزعفران.",
      basePrice: "0.350",
      images: [{ url: img("1571934811356-5cc061b6821f"), isPrimary: true }],
      tags: ["drink"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_knafeh",
      categoryId: "cat_sweets",
      name: "Knafeh Nabulsiyeh",
      nameAr: "كنافة نابلسية",
      description: "Stretchy akkawi cheese under crisp semolina, sugar syrup, pistachio.",
      descriptionAr: "جبنة عكاوي تحت طبقة سميد مقرمشة مع قطر وفستق.",
      basePrice: "1.750",
      images: [{ url: img("1631206753348-db44968fd440"), isPrimary: true }],
      tags: ["sweet"],
      vegetarian: true,
      popular: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
    {
      id: "p_baklava",
      categoryId: "cat_sweets",
      name: "Baklava Selection",
      nameAr: "تشكيلة بقلاوة",
      description: "Six pieces of layered filo, pistachio and walnut, light syrup.",
      descriptionAr: "ست قطع من البقلاوة بالفستق والجوز وقطر خفيف.",
      basePrice: "2.250",
      images: [{ url: img("1519676867240-f03562e64548"), isPrimary: true }],
      tags: ["sweet"],
      vegetarian: true,
      hasVariants: false,
      variants: [],
      modifierGroups: [],
    },
  ],
};
